### PR TITLE
Cache Directory (assets)

### PR DESCRIPTION
**Pull request by davidsosavaldes**
In `Pipeline` class on `getCacheDirectory` method, the CACHE_DIRECTORY changes from:

    $this->getOption('CACHE_DIRECTORY')

to: 

    $this->getOption('CACHE_DIRECTORY').'assets/'

When the `Sprockets\Cache` class gets the CACHE_DIRECTORY from the `Pipeline` class it gets incomplete, so i change it with the method `getCacheDirectory()`, i think this is the expected output in first instance.

### CODE REVIEW

**Comment by vendethiel** [comment]
Sounds good, however I'd like to check one of my bigger projects using this to make sure that wasn't a decision I took 4 years ago and can't remember now :)

**Comment by davidsosavaldes** [comment]
I've been tested this a lot of time and couldn't find another explanation 👍

**Comment by vendethiel** [comment]
:+1: thanks :)

**Comment by davidsosavaldes** [comment]
You're awesome man, thanks to you!!

**Comment by davidsosavaldes** [comment]
Also i forget to tell you, could you please create a new release please?

**Comment by vendethiel** [comment]
sure, give me some time to get a computer.

**Comment by vendethiel** [comment]
There, 2.1.4 tagged.

**Comment by vendethiel** [comment]
Also added you as a collaborator, though I'd still prefer to use pull requests for code changes :).

**Comment by davidsosavaldes** [comment]
That's a great honor, and don't worry about it, we can still continue to work with pull requests.

Thank you for your trust 💯

**Comment by vendethiel** [comment]
Ah, [found the catch](https://github.com/vendethiel/Sprockets-PHP/blob/master/lib/Sprockets/Filter/Css.php#L14). I'll publish a patch.

**Pull request merged**
