### PR TITLE
Overwrite the file list dependencies

### PR DESCRIPTION
**Pull request by davidsosavaldes**
I have a problem:

Having two controller methods calling different javascript and stylesheet files, if i want to change the manifest from A to B (as an option argument) in `Cache` class, the `isFresh()` method couldn't detect the dependency changes.

Maybe we could force it passing an option argument called `force`.

    $cache = new Sprockets\Cache($pipeline, 'css', $vars = array(), $options = array(
        'force' => TRUE
    ));

### CODE REVIEW

**Comment by vendethiel** [comment]
Ugh, the code's smelly...  Why do I have this static `current_instance`?!

**Comment by vendethiel** [comment]
c7930b433ced8587d4ef036c49df4b9b590389e4

**Comment by vendethiel** [comment]
WRT your PR, it seems to me `Cache::getDependenciesFilename` should include `$this->pipeline->getManifestName()`, no?

**Comment by davidsosavaldes** [comment]
that should do the trick (fcbdbfd), don't you think?

**Comment by vendethiel** [comment]
Well, does it work for you?

**Comment by davidsosavaldes** [comment]
Yes, now i have multiple dependency files, this works perfectly!

**Comment by vendethiel** [comment]
Okay, good. I'll try to see if I can write some tests before merging, but just in case I forget, ping me during the weekend and I'll merge it.

**Comment by davidsosavaldes** [comment]
ack

**Comment by vendethiel** [comment]
Thanks! :star:

**Comment by davidsosavaldes** [comment]
Thanks for your time and support!!

**Pull request merged**
