### PR TITLE
Add more font file extensions, and fix CSS filter url path

### PR DESCRIPTION
**Pull request by davidsosavaldes**
Hello again my friend @vendethiel!

I realize that there are missing some *Font* extensions, so i added for you. 

Also, replace all occurrences of "//" as long as they are not preceded by ":"  in `Sprockets\Filter\CSS` class.

### CODE REVIEW

**Comment by vendethiel** [comment]
mmmh, what's the second part fixing? I'd like to add a test for that :).

Thanks!

**Comment by davidsosavaldes** [comment]
When i add the font extensions, the URL of CSS files changed. Here's an example:

    @font-face {
        font-family: 'Glyphicons Halflings';
        src: url(../../../..//path/to/assets/fonts/glyphicons-halflings-regular.eot);
    }

That's why i added the regex: `'/(?<!:)\/\//'`, and now:

    @font-face {
        font-family: 'Glyphicons Halflings';
        src: url(../../../../path/to/assets/fonts/glyphicons-halflings-regular.eot); //without '//'
    }

**Comment by vendethiel** [comment]
mh; what's your initial `src: url(..)`?

**Comment by davidsosavaldes** [comment]
src: url('glyphicons-halflings-regular.eot');

**Comment by vendethiel** [comment]
and what are you PATHS like?

**Comment by davidsosavaldes** [comment]
{
        "template": {
            "directories": [
                "/path/to/application/themes/bootstrap/assets/",
                "/path/to/application/themes/_shared/assets/"
            ],
            "prefixes": {
                "js": "javascripts",
                "css": "stylesheets",
                "img": "images",
                "font": "fonts"
            }
        },
        "external": {
            "directories": [
                "/path/to/application/bower_components/"
            ]
        },
        "CACHE_DIRECTORY": "/path/to/application/public/assets/"
    }

**Comment by vendethiel** [comment]
those shouldn't have leading slashes, I think. It wasn't designed that way :)

**Comment by davidsosavaldes** [comment]
Oh...my bad, but there may be someone out there who also implemented in the same way. I think it doesn't hurt if you implement this validation, what do you think?

**Comment by vendethiel** [comment]
Certainly doesn't. Would you mind changing one of the test's path by adding a prefix slash?

**Comment by davidsosavaldes** [comment]
This could be the test scenario

**Comment by vendethiel** [comment]
mmh, I'll take this one.

**Comment by vendethiel** [comment]
Thanks.

**Comment by davidsosavaldes** [comment]
I'll take that cake, thank you!

**Pull request merged**
